events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    upstream admin_api {
        least_conn;
        server api:8000 max_fails=3 fail_timeout=15s;
        keepalive 32;
        keepalive_requests 1000;
        keepalive_timeout 60s;
    }

    upstream grpc_ingester {
        least_conn;
        server grpc-ingester:50051 max_fails=3 fail_timeout=15s;
    }

    server {
        listen 80;
        http2 on;

        location /memory_stream.MemoryStream/ {
            grpc_pass grpc://grpc_ingester;

            grpc_read_timeout 1h;
            grpc_send_timeout 1h;
            client_body_timeout 1h;
            client_max_body_size 0;
        }

        location / {
            proxy_pass http://admin_api;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
