[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bananbka", email = "bananbka0.2@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "argon2-cffi>=23.1.0",
    "fastapi>=0.125.0",
    "pydantic[email]>=2.9.0",
    "shared",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.38.0",
]

[tool.uv.sources]
shared = { workspace = true }

[project.scripts]
api = "api:main"
seed-admin = "api.seed_admin:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
