"""Turn k6 --summary-export files into tables + charts.

    uv run --with matplotlib python load-tests/summarize.py

Writes load-tests/results/REPORT.md and load-tests/charts/*.png.
"""

# ruff: noqa: E501
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent
RES = ROOT / "results"
CHARTS = ROOT / "charts"
LEVELS = [2, 5, 10, 25, 50, 100, 200]
SCEN = {"A": "A read-intensive", "B": "B write-intensive", "C": "C complex workflow"}


def load(name: str) -> dict | None:
    path = RES / f"{name}.json"
    if not path.exists():
        return None
    m = json.loads(path.read_text())["metrics"]
    d = m["http_req_duration{phase:main}"]
    reqs = m["http_reqs{phase:main}"]
    failed = m["http_req_failed{phase:main}"]
    rows = RES / f"{name}.dbrows"
    return {
        "rps": reqs["rate"],
        "count": reqs["count"],
        "avg": d["avg"],
        "p50": d["med"],
        "p95": d["p(95)"],
        "p99": d["p(99)"],
        "err": failed["value"] * 100,
        "dbrows": int(rows.read_text()) if rows.exists() else None,
        "brows": int((RES / f"{name}.backupsrows").read_text())
        if (RES / f"{name}.backupsrows").exists()
        else None,
    }


def fmt_row(label: str, r: dict) -> str:
    return (
        f"| {label} | {r['rps']:.0f} | {r['avg']:.0f} | {r['p50']:.0f} | "
        f"{r['p95']:.0f} | {r['p99']:.0f} | {r['err']:.2f} |"
    )


HEAD = (
    "| VUs | Throughput (RPS) | Avg ms | p50 ms | p95 ms | p99 ms | Error % |\n"
    "| --- | --- | --- | --- | --- | --- | --- |"
)


def saturation(points: list[tuple[int, dict]]) -> str:
    """Smallest load level that already reaches >=90% of the peak throughput."""
    peak_vus, peak = max(points, key=lambda p: p[1]["rps"])
    for v, r in points:
        if r["rps"] >= 0.9 * peak["rps"]:
            return (
                f"~{v} VUs ({r['rps']:.0f} RPS = {100 * r['rps'] / peak['rps']:.0f}% of "
                f"the {peak['rps']:.0f} RPS peak seen at {peak_vus} VUs); more VUs only "
                "add latency"
            )
    return "n/a"


def main() -> None:
    CHARTS.mkdir(exist_ok=True)
    out = ["# Lab 5 results (generated by load-tests/summarize.py)\n"]
    data: dict[str, list[tuple[int, dict]]] = {}
    for s in SCEN:
        pts = [(v, r) for v in LEVELS if (r := load(f"matrix_{s}_{v}"))]
        data[s] = pts
        if not pts:
            continue
        out += [f"## Scenario {SCEN[s]} (2 api instances)\n", HEAD]
        out += [fmt_row(f"{v}", r) for v, r in pts]
        out += [f"\nSaturation point: {saturation(pts)}\n"]

    out.append("## Scaling impact (100 VUs)\n")
    out.append(
        "| Scenario | Instances | RPS | p95 ms | p99 ms | Error % | Efficiency vs 1 instance |\n"
        "| --- | --- | --- | --- | --- | --- | --- |"
    )
    for s in ("A", "B"):
        base = load(f"scale1_{s}_100")
        for n, name in (
            (1, f"scale1_{s}_100"),
            (2, f"matrix_{s}_100"),
            (3, f"scale3_{s}_100"),
        ):
            r = load(name)
            if not r or not base:
                continue
            eff = r["rps"] / (n * base["rps"])
            out.append(
                f"| {SCEN[s]} | {n} | {r['rps']:.0f} | {r['p95']:.0f} | {r['p99']:.0f} | "
                f"{r['err']:.2f} | {eff:.2f} ({r['rps'] / base['rps']:.2f}x throughput) |"
            )

    warm, cold = load("matrix_A_100"), load("nocache_A_100")
    if warm and cold:
        out += [
            "\n## Caching impact (scenario A, 100 VUs, 2 instances)\n",
            "| Mode | RPS | p50 ms | p95 ms | p99 ms | Error % | memory_backups rows read |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            f"| cache disabled (`Cache-Control: no-cache`) | {cold['rps']:.0f} | {cold['p50']:.0f} | "
            f"{cold['p95']:.0f} | {cold['p99']:.0f} | {cold['err']:.2f} | {cold['brows']:,} |",
            f"| cache enabled (warm) | {warm['rps']:.0f} | {warm['p50']:.0f} | "
            f"{warm['p95']:.0f} | {warm['p99']:.0f} | {warm['err']:.2f} | {warm['brows']:,} |",
        ]
    (RES / "REPORT.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("\n".join(out))

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib missing: charts skipped")
        return

    fig, ax = plt.subplots(figsize=(7, 4))
    for s, pts in data.items():
        if pts:
            ax.plot(
                [v for v, _ in pts],
                [r["rps"] for _, r in pts],
                marker="o",
                label=SCEN[s],
            )
    ax.set(
        xlabel="Virtual users", ylabel="Throughput (req/s)", title="Throughput vs load"
    )
    ax.grid(alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(CHARTS / "throughput.png", dpi=130)

    fig, axes = plt.subplots(1, 3, figsize=(13, 4), sharey=False)
    for ax, (s, pts) in zip(axes, data.items(), strict=False):
        if not pts:
            continue
        xs = [v for v, _ in pts]
        for key in ("p50", "p95", "p99"):
            ax.plot(xs, [r[key] for _, r in pts], marker="o", label=key)
        ax.set(title=SCEN[s], xlabel="Virtual users", ylabel="Latency (ms)")
        ax.set_yscale("log")
        ax.grid(alpha=0.3, which="both")
        ax.legend()
    fig.tight_layout()
    fig.savefig(CHARTS / "latency.png", dpi=130)
    print(f"charts written to {CHARTS}")


if __name__ == "__main__":
    main()
