FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY shared ./shared
COPY services ./services

RUN pip install --no-cache-dir uv && uv sync --package grpc-ingester --frozen

EXPOSE 50051

CMD ["uv", "run", "grpc-ingester"]
